"""Report generation service"""
from datetime import datetime
from typing import List, Dict


def generate_debrief_report(
    session_id: str,
    moments: List[Dict],
    evaluations: List[Dict],
    student_name: str = "Student",
    evaluator_name: str = "Dr. Evaluator"
) -> str:
    """Generate markdown debrief report"""

    # Filter relevant moments
    relevant_moments = [
        (m, e) for m, e in zip(moments, evaluations)
        if e.get('moment_relevant', True) != False
    ]

    # Calculate statistics
    total_moments = len(relevant_moments)
    avg_scores = {}

    if evaluations:
        rubric_keys = ['team_communication', 'technical_skills', 'response_time', 'leadership', 'overall']
        for key in rubric_keys:
            scores = [
                e.get('rubric_scores', {}).get(key)
                for e in evaluations
                if e.get('rubric_scores', {}).get(key) is not None
            ]
            if scores:
                avg_scores[key] = sum(scores) / len(scores)

    # Generate report
    report = f"""# Clinical Simulation Debrief Report

**Session:** {session_id}
**Date:** {datetime.now().strftime('%B %d, %Y')}
**Student:** {student_name}
**Evaluator:** {evaluator_name}

---

## Summary

- **Total Critical Moments Reviewed:** {total_moments}
- **Overall Performance:** {avg_scores.get('overall', 0):.1f}/5

### Performance Breakdown
| Category | Score |
|----------|-------|
| Team Communication | {avg_scores.get('team_communication', 0):.1f}/5 |
| Technical Skills | {avg_scores.get('technical_skills', 0):.1f}/5 |
| Response Time | {avg_scores.get('response_time', 0):.1f}/5 |
| Leadership | {avg_scores.get('leadership', 0):.1f}/5 |

---

## Critical Moments Review

"""

    # Add each moment
    for idx, (moment, evaluation) in enumerate(relevant_moments, 1):
        report += f"""### Moment #{idx} - {moment.get('start_time_formatted', 'N/A')} to {moment.get('end_time_formatted', 'N/A')}

**Clinical Significance:**
{evaluation.get('edited_description', moment.get('clinical_significance', 'N/A'))}

**Evidence Sources:** {moment.get('num_sources', 0)}/4
**Confidence:** {int(moment.get('confidence', 0) * 100)}%

#### Feedback to Student

**✓ What Went Well:**
{evaluation.get('student_feedback', {}).get('positive', 'N/A')}

**⚠ Areas for Improvement:**
{evaluation.get('student_feedback', {}).get('negative', 'N/A')}

**📚 Key Learning Points:**
{evaluation.get('student_feedback', {}).get('learningPoints', 'N/A')}

#### Performance Scores
"""

        rubric_scores = evaluation.get('rubric_scores', {})
        for key, label in [
            ('team_communication', 'Team Communication'),
            ('technical_skills', 'Technical Skills'),
            ('response_time', 'Response Time'),
            ('leadership', 'Leadership')
        ]:
            score = rubric_scores.get(key, 'N/A')
            report += f"- {label}: {score}/5\n"

        report += "\n---\n\n"

    # Add recommendations
    report += f"""## Overall Recommendations

Based on the {total_moments} critical moments reviewed:

"""

    # Aggregate all learning points
    all_learning_points = [
        e.get('student_feedback', {}).get('learningPoints', '')
        for e in evaluations
        if e.get('student_feedback', {}).get('learningPoints')
    ]

    if all_learning_points:
        report += "**Key Areas for Development:**\n"
        for i, point in enumerate(all_learning_points[:5], 1):
            report += f"{i}. {point}\n"
        report += "\n"

    report += f"""
**Next Steps:**
1. Review recorded footage for the highlighted moments
2. Discuss team coordination opportunities
3. Practice identified scenarios in future simulations

---

*Report generated by Clinical Simulation Review System*
*Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""

    return report
