#!/usr/bin/env python3
"""
Head Pose Estimation using 6DRepNet360 on Light-ASD face tracks.

For each face track from Light-ASD, crops the face from video frames
and estimates yaw/pitch/roll using 6DRepNet360.

Output: JSON with per-track, per-frame head pose (yaw, pitch, roll).

Note: pickle is used to load Light-ASD output (tracks.pckl) generated by our pipeline.
The model's eval() call is a standard PyTorch method to set inference mode, not code execution.
"""

import sys
import json
import pickle  # Required: Light-ASD outputs are in pickle format (tracks.pckl)

from scripts.core.records import (
    LIGHT_ASD_ANALYSIS_FPS,
    light_asd_index_to_source_frame,
)
import math
import argparse
from pathlib import Path

from scripts.core.records import canonical_track_id, sha256_file


def load_model(repository_path, weights_path, weights_sha256, device="cuda"):
    """Load 6DRepNet360 exclusively from checked local code and weights."""
    repository_path = Path(repository_path).resolve()
    weights_path = Path(weights_path).resolve()
    package_path = repository_path / "sixdrepnet360"
    if not (package_path / "test.py").is_file():
        raise FileNotFoundError(f"Pinned 6DRepNet360 checkout is required: {repository_path}")
    if not weights_path.is_file():
        raise FileNotFoundError(f"Local 6DRepNet360 weights are required: {weights_path}")
    actual = sha256_file(weights_path)
    if actual != weights_sha256:
        raise ValueError(
            f"6DRepNet360 weights checksum mismatch: expected {weights_sha256}, got {actual}"
        )
    sys.path.insert(0, str(package_path))
    global cv2, np, torch, torchvision, transforms, repnet_utils
    import cv2
    import numpy as np
    import torch
    import torchvision
    from torchvision import transforms
    import utils as repnet_utils
    from test import SixDRepNet360
    model = SixDRepNet360(torchvision.models.resnet.Bottleneck, [3, 4, 6, 3], 6)
    saved_state_dict = torch.load(weights_path, map_location=device, weights_only=True)
    if 'model_state_dict' in saved_state_dict:
        model.load_state_dict(saved_state_dict['model_state_dict'])
    else:
        model.load_state_dict(saved_state_dict)
    model.to(device)
    # Set model to inference mode (standard PyTorch method)
    model.train(False)
    return model


def load_light_asd_tracks(pywork_dir):
    """Load face tracks from Light-ASD output."""
    pywork = Path(pywork_dir)
    with open(pywork / 'tracks.pckl', 'rb') as f:
        tracks = pickle.load(f)
    return tracks


def filter_tracks(tracks, min_duration_s):
    """Keep only tracks lasting at least min_duration_s."""
    filtered = []
    for i, track in enumerate(tracks):
        frames = track['track']['frame']
        # These indices are Light-ASD's own 25 Hz numbering; dividing by the source rate
        # would understate every track's duration by ~17% and drop real tracks at the
        # minimum-duration filter.
        duration = (max(frames) - min(frames)) / LIGHT_ASD_ANALYSIS_FPS
        if duration >= min_duration_s:
            filtered.append((i, track, duration))
    return filtered


def estimate_head_poses(video_path, tracks_to_process, model, fps, device="cuda",
                        batch_size=32, sample_rate=5):
    """
    Estimate head pose for each face in each track.

    Args:
        video_path: Path to video file
        tracks_to_process: List of (track_idx, track_data, duration)
        model: 6DRepNet360 model
        device: cuda/cpu
        fps: Video frame rate
        batch_size: Batch size for inference
        sample_rate: Process every Nth frame (1=all, 5=every 5th)

    Returns:
        Dict of track_idx -> list of {frame, yaw, pitch, roll, bbox}
    """
    transform = transforms.Compose([
        transforms.ToPILImage(),
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # Build frame-to-tracks lookup: which faces need to be cropped per frame
    frame_tasks = {}  # frame_num -> [(track_idx, bbox_idx)]
    for track_idx, track, _ in tracks_to_process:
        frames = track['track']['frame']
        bboxes = track['track']['bbox']  # [x1, y1, x2, y2] format

        for j in range(0, len(frames), sample_rate):
            frame_num = frames[j]
            if frame_num not in frame_tasks:
                frame_tasks[frame_num] = []
            frame_tasks[frame_num].append((track_idx, j, bboxes[j]))

    # Light-ASD indices count its own 25 Hz re-encode, so they cannot address the source
    # video directly: index 4500 is 180.0s of analysis but only 150.2s of a 29.97 fps
    # source. Map each analysis index to the source frame showing the same instant, and
    # keep the mapping so results are reported on the analysis timebase.
    source_frame_by_analysis = {
        analysis_frame: light_asd_index_to_source_frame(analysis_frame, fps)
        for analysis_frame in frame_tasks
    }
    analysis_by_source = {
        source: analysis for analysis, source in source_frame_by_analysis.items()
    }
    sorted_frames = sorted(analysis_by_source)
    if not sorted_frames:
        return {}

    print(f"    Processing {len(sorted_frames)} unique frames, "
          f"{sum(len(v) for v in frame_tasks.values())} face crops total")

    # Open video
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {video_path}")

    video_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    video_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))

    results = {}  # track_idx -> list of pose dicts
    batch_crops = []  # (track_idx, frame_num, crop_tensor)
    batch_meta = []

    frame_idx = 0
    target_idx = 0

    while target_idx < len(sorted_frames):
        target_frame = sorted_frames[target_idx]

        # Seek if we're far behind
        if target_frame - frame_idx > 100:
            cap.set(cv2.CAP_PROP_POS_FRAMES, target_frame)
            frame_idx = target_frame

        ret, frame = cap.read()
        if not ret:
            break

        if frame_idx == target_frame:
            # Process all face crops for this frame
            for track_idx, bbox_j, bbox in frame_tasks[analysis_by_source[target_frame]]:
                # Light-ASD bbox format: [x1, y1, x2, y2]
                bx1, by1, bx2, by2 = bbox
                # Add 20% padding around the face
                w, h = bx2 - bx1, by2 - by1
                pad_w, pad_h = w * 0.2, h * 0.2
                x1 = max(0, int(bx1 - pad_w))
                y1 = max(0, int(by1 - pad_h))
                x2 = min(video_w, int(bx2 + pad_w))
                y2 = min(video_h, int(by2 + pad_h))

                if x2 - x1 < 10 or y2 - y1 < 10:
                    continue

                face_crop = frame[y1:y2, x1:x2]
                face_rgb = cv2.cvtColor(face_crop, cv2.COLOR_BGR2RGB)

                try:
                    tensor = transform(face_rgb)
                    batch_crops.append(tensor)
                    batch_meta.append({
                        'track_idx': track_idx,
                        'frame': analysis_by_source[target_frame],
                        'bbox': [x1, y1, x2, y2]
                    })
                except Exception:
                    continue

            # Run batch inference when batch is full
            if len(batch_crops) >= batch_size:
                _run_batch(model, batch_crops, batch_meta, results, device)
                batch_crops = []
                batch_meta = []

            target_idx += 1

        frame_idx += 1

    # Process remaining batch
    if batch_crops:
        _run_batch(model, batch_crops, batch_meta, results, device)

    cap.release()
    return results


def _run_batch(model, batch_crops, batch_meta, results, device):
    """Run inference on a batch of face crops."""
    batch_tensor = torch.stack(batch_crops).to(device)

    with torch.no_grad():
        R_pred = model(batch_tensor)
        euler = repnet_utils.compute_euler_angles_from_rotation_matrices(R_pred) * 180 / math.pi
        pitches = euler[:, 0].cpu().numpy()
        yaws = euler[:, 1].cpu().numpy()
        rolls = euler[:, 2].cpu().numpy()

    for i, meta in enumerate(batch_meta):
        track_idx = meta['track_idx']
        if track_idx not in results:
            results[track_idx] = []
        results[track_idx].append({
            'frame': int(meta['frame']),
            'yaw': float(yaws[i]),
            'pitch': float(pitches[i]),
            'roll': float(rolls[i]),
            'bbox': meta['bbox'],
        })


def summarize_poses(pose_results, tracks_to_process):
    """Print summary statistics for each track's head pose."""
    for track_idx, _, duration in tracks_to_process:
        if track_idx not in pose_results:
            continue
        poses = pose_results[track_idx]
        yaws = [p['yaw'] for p in poses]
        pitches = [p['pitch'] for p in poses]

        print(f"    Track {track_idx} ({duration:.1f}s, {len(poses)} samples):")
        print(f"      Yaw:   mean={np.mean(yaws):>7.1f}, std={np.std(yaws):>5.1f}, "
              f"range=[{np.min(yaws):>7.1f}, {np.max(yaws):>7.1f}]")
        print(f"      Pitch: mean={np.mean(pitches):>7.1f}, std={np.std(pitches):>5.1f}, "
              f"range=[{np.min(pitches):>7.1f}, {np.max(pitches):>7.1f}]")


def main():
    parser = argparse.ArgumentParser(description="Head pose estimation on Light-ASD face tracks")
    parser.add_argument('--video', required=True, help='Path to video file')
    parser.add_argument('--asd-pywork', required=True, help='Path to Light-ASD pywork directory')
    parser.add_argument('--output', required=True, help='Output JSON path')
    parser.add_argument('--camera', required=True, choices=['cam1', 'cam2', 'cam3'])
    parser.add_argument('--repository-path', required=True)
    parser.add_argument('--weights-path', required=True)
    parser.add_argument('--weights-sha256', required=True)
    parser.add_argument('--device', default='cuda')
    # No duration floor by default. Head pose must cover every track that best-angle
    # selection is allowed to choose, and selection considers any linked fragment. A 10s
    # floor left pose available for 42 of 538 tracks on session_001, so 161 of 242 selected
    # segments had no pose for their selected track and Stage 9 classified nothing at all.
    # This is a consistency fix between two track universes, not a quality threshold: the
    # gaze stage keeps its own pose-usability and calibration gates unchanged.
    parser.add_argument('--min-track-duration', type=float, default=0.0)
    parser.add_argument('--sample-rate', type=int, default=5,
                        help='Process every Nth frame (default: 5)')
    parser.add_argument('--batch-size', type=int, default=32)
    parser.add_argument('--fps', type=float, required=True,
                        help='Measured FPS from the synchronized stream manifest')
    args = parser.parse_args()

    print("=" * 70)
    print("HEAD POSE ESTIMATION (6DRepNet360)")
    print("=" * 70)

    # Load Light-ASD tracks
    print("\n[1/4] Loading Light-ASD face tracks...")
    all_tracks = load_light_asd_tracks(args.asd_pywork)
    print(f"  -> {len(all_tracks)} total tracks")

    # Filter significant tracks
    print(f"\n[2/4] Filtering tracks (>{args.min_track_duration}s)...")
    tracks_to_process = filter_tracks(all_tracks, args.min_track_duration)
    print(f"  -> {len(tracks_to_process)} significant tracks")
    for idx, _, dur in tracks_to_process:
        print(f"    Track {idx}: {dur:.1f}s")

    # Load model
    print("\n[3/4] Loading 6DRepNet360 model...")
    model = load_model(
        args.repository_path, args.weights_path, args.weights_sha256, args.device
    )
    print(f"  -> Model loaded on {args.device}")

    # Run estimation
    print(f"\n[4/4] Estimating head poses (sample_rate={args.sample_rate})...")
    pose_results = estimate_head_poses(
        args.video, tracks_to_process, model, args.fps, args.device,
        args.batch_size, args.sample_rate
    )

    # Frame size of the video the boxes were measured in. Probed here rather than
    # passed down so the metadata records it even when no pose was produced.
    _probe = cv2.VideoCapture(str(args.video))
    video_width = int(_probe.get(cv2.CAP_PROP_FRAME_WIDTH))
    video_height = int(_probe.get(cv2.CAP_PROP_FRAME_HEIGHT))
    _probe.release()
    if video_width <= 0 or video_height <= 0:
        raise RuntimeError(f"could not probe frame size for {args.video}")

    # Summary
    print("\n  Head pose summary:")
    summarize_poses(pose_results, tracks_to_process)

    # Save output
    output_data = {
        'tracks': {},
        'metadata': {
            'video': args.video,
            'asd_pywork': args.asd_pywork,
            'sample_rate': args.sample_rate,
            'min_track_duration': args.min_track_duration,
            'fps': LIGHT_ASD_ANALYSIS_FPS,
            'analysis_fps': LIGHT_ASD_ANALYSIS_FPS,
            'source_fps': args.fps,
            # Poses carry pixel bounding boxes, so the frame size they are relative to
            # must travel with them. Without it the gaze stage cannot normalise a box and
            # discards every pose: session_001 reported no usable pose in all 242 selected
            # segments purely because this field was absent.
            'resolution': [video_width, video_height],
            'total_tracks_processed': len(tracks_to_process),
        }
    }

    for track_idx, poses in pose_results.items():
        output_data['tracks'][canonical_track_id(args.camera, str(track_idx))] = {
            'poses': poses,
            'summary': {
                'num_samples': len(poses),
                'mean_yaw': float(np.mean([p['yaw'] for p in poses])),
                'mean_pitch': float(np.mean([p['pitch'] for p in poses])),
                'mean_roll': float(np.mean([p['roll'] for p in poses])),
                'std_yaw': float(np.std([p['yaw'] for p in poses])),
                'std_pitch': float(np.std([p['pitch'] for p in poses])),
                'std_roll': float(np.std([p['roll'] for p in poses])),
            }
        }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w') as f:
        json.dump(output_data, f, indent=2)

    total_samples = sum(len(p) for p in pose_results.values())
    print(f"\nSaved {total_samples} pose estimates across "
          f"{len(pose_results)} tracks to {args.output}")


if __name__ == "__main__":
    main()
